// testCrud.js - API endpoint verification script
const assert = require('assert').strict;

async function runTests() {
  const baseUrl = 'http://localhost:3000';
  console.log('Starting BlogSphere verification tests...');

  try {
    // 1. Test GET / (Home Page)
    console.log('Testing GET / (Home Page)...');
    const homeRes = await fetch(baseUrl + '/');
    assert.equal(homeRes.status, 200, 'Home Page should return status 200');
    const homeText = await homeRes.text();
    assert.match(homeText, /Welcome to BlogSphere/i, 'Home Page should contain heading');
    console.log('✅ GET / passed.');

    // 2. Test GET /posts (All Blogs)
    console.log('Testing GET /posts (All Blogs)...');
    const postsRes = await fetch(baseUrl + '/posts');
    assert.equal(postsRes.status, 200, 'Blogs page should return status 200');
    const postsText = await postsRes.text();
    assert.match(postsText, /All Blog Stories/i, 'Blogs page should contain header');
    console.log('✅ GET /posts passed.');

    // 3. Test GET /about (About Page)
    console.log('Testing GET /about (About)...');
    const aboutRes = await fetch(baseUrl + '/about');
    assert.equal(aboutRes.status, 200, 'About page should return status 200');
    const aboutText = await aboutRes.text();
    assert.match(aboutText, /About BlogSphere/i, 'About page should contain header');
    console.log('✅ GET /about passed.');

    // 4. Test POST /posts (Validation failure)
    console.log('Testing POST /posts (Empty validation)...');
    // Sending empty body
    const emptyForm = new URLSearchParams();
    emptyForm.append('title', '');
    emptyForm.append('author', '');
    emptyForm.append('content', '');

    const failCreateRes = await fetch(baseUrl + '/posts', {
      method: 'POST',
      body: emptyForm,
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' }
    });
    
    assert.equal(failCreateRes.status, 400, 'Empty post submission should return 400 Bad Request');
    const failCreateText = await failCreateRes.text();
    assert.match(failCreateText, /Validation Failed/i, 'Error page should show Validation Failed banner');
    assert.match(failCreateText, /Please enter a blog title/i, 'Error text should contain empty title warning');
    console.log('✅ Server-side validation checks passed.');

    // 5. Test POST /posts (Successful creation)
    console.log('Testing POST /posts (Successful Creation)...');
    const validForm = new URLSearchParams();
    validForm.append('title', 'My Automated Test Blog');
    validForm.append('author', 'Tester Bot');
    validForm.append('content', 'This is content generated by the automated test runner script to verify dynamic EJS list updates.');

    // Note: Node fetch doesn't follow redirect automatically unless configured,
    // but default behavior returns the redirect response status. Let's disable redirect to inspect the Location header.
    const createRes = await fetch(baseUrl + '/posts', {
      method: 'POST',
      body: validForm,
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      redirect: 'manual'
    });

    assert.equal(createRes.status, 302, 'Successful creation should redirect (302)');
    const redirectUrl = createRes.headers.get('location');
    assert.ok(redirectUrl, 'Redirect location header should be set');
    console.log(`✅ POST /posts creation passed. Redirects to: ${redirectUrl}`);

    // Resolve post ID from redirection URL
    const postId = redirectUrl.split('/').pop();
    console.log(`Extracted created post ID: ${postId}`);

    // 6. Test GET /posts/:id (Detail page)
    console.log(`Testing GET /posts/${postId} (Detail Page)...`);
    const detailRes = await fetch(baseUrl + redirectUrl);
    assert.equal(detailRes.status, 200, 'Created post detail page should return 200');
    const detailText = await detailRes.text();
    assert.match(detailText, /My Automated Test Blog/i, 'Detail page should render post title');
    assert.match(detailText, /Tester Bot/i, 'Detail page should render post author');
    console.log('✅ GET /posts/:id detail page passed.');

    // 7. Test POST /posts/:id/edit (Validation failure)
    console.log(`Testing POST /posts/${postId}/edit (Validation Failure)...`);
    const invalidEditForm = new URLSearchParams();
    invalidEditForm.append('title', '');
    invalidEditForm.append('author', 'Tester Bot');
    invalidEditForm.append('content', 'Content');

    const failEditRes = await fetch(baseUrl + `/posts/${postId}/edit`, {
      method: 'POST',
      body: invalidEditForm,
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' }
    });
    assert.equal(failEditRes.status, 400, 'Invalid update should return 400');
    const failEditText = await failEditRes.text();
    assert.match(failEditText, /Please enter a blog title/i, 'Should render error warning');
    console.log('✅ Edit validation checks passed.');

    // 8. Test POST /posts/:id/edit (Successful update)
    console.log(`Testing POST /posts/${postId}/edit (Successful Update)...`);
    const validEditForm = new URLSearchParams();
    validEditForm.append('title', 'Updated Test Title');
    validEditForm.append('author', 'Tester Bot');
    validEditForm.append('content', 'This is updated content.');

    const editRes = await fetch(baseUrl + `/posts/${postId}/edit`, {
      method: 'POST',
      body: validEditForm,
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      redirect: 'manual'
    });
    assert.equal(editRes.status, 302, 'Successful edit should redirect (302)');
    console.log('✅ POST /posts/:id/edit passed.');

    // 9. Test GET /posts/:id (Verify updated details)
    console.log(`Testing GET /posts/${postId} (Verify update contents)...`);
    const verifyRes = await fetch(baseUrl + `/posts/${postId}`);
    const verifyText = await verifyRes.text();
    assert.match(verifyText, /Updated Test Title/i, 'Post title should show updated title');
    console.log('✅ Updated content verification passed.');

    // 10. Test POST /posts/:id/delete (Successful delete)
    console.log(`Testing POST /posts/${postId}/delete (Delete Post)...`);
    const deleteRes = await fetch(baseUrl + `/posts/${postId}/delete`, {
      method: 'POST',
      redirect: 'manual'
    });
    assert.equal(deleteRes.status, 302, 'Delete post should redirect (302)');
    assert.equal(deleteRes.headers.get('location'), '/posts', 'Deletion should redirect to all posts (/posts)');
    console.log('✅ POST /posts/:id/delete passed.');

    // 11. Test GET /posts/:id (Confirm deletion)
    console.log(`Testing GET /posts/${postId} (Verify deleted - 404)...`);
    const checkDeletedRes = await fetch(baseUrl + `/posts/${postId}`);
    assert.equal(checkDeletedRes.status, 404, 'Deleted post details should return 404');
    const checkDeletedText = await checkDeletedRes.text();
    assert.match(checkDeletedText, /Page Not Found/i, 'Should render 404 template');
    console.log('✅ Post deletion verified.');

    // 12. Test Wildcard 404 Route
    console.log('Testing GET /some-random-route (Wildcard 404)...');
    const wildcardRes = await fetch(baseUrl + '/some-random-route');
    assert.equal(wildcardRes.status, 404, 'Invalid routes should return 404');
    const wildcardText = await wildcardRes.text();
    assert.match(wildcardText, /Page Not Found/i, 'Should render 404 page content');
    console.log('✅ Wildcard 404 verification passed.');

    console.log('\n🎉 ALL TESTS COMPLETED SUCCESSFULLY! BlogSphere MVP routing, CRUD, and validations are fully operational! 🎉');
  } catch (error) {
    console.error('❌ Test failed with error:', error);
    process.exit(1);
  }
}

runTests();
